version: "3"
services:
  cardoc-backend:
    container_name: cardoc-backend
    build:
      context: .
      dockerfile: ./Dockerfile-deploy
    depends_on:
      - cardoc-db
    restart: always
    environment:
      SQL_HOST: cardoc-db
      SQL_PORT: 5432
      DJANGO_SETTINGS_MODULE: cardoc.settings.deploy
    env_file:
    - .dockerenv.deploy.backend
    command:
      - bash
      - -c
      - |
        python manage.py wait_for_db -t 120
        python manage.py migrate
        gunicorn cardoc.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
  cardoc-db:
    container_name: cardoc-db
    image: postgres:14
    restart: always
    command: postgres -c listen_addresses='*'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --auth-host=scram-sha-256
      - TZ="Asia/Seoul"
    env_file:
      - .dockerenv.deploy.db
  cardoc-nginx: 
    image: nginx:1.21
    container_name: cardoc-nginx
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "8061:8061" 
    environment:
      - TZ="Asia/Seoul"
    depends_on:
      - cardoc-backend